// Vietnamese catalog. Type-only import avoids a runtime dependency cycle.
import type { en } from './i18n';

export const vi: Record<keyof typeof en, string> = {
  'settings.languageSaveFailed': 'Không thể lưu ngôn ngữ. Vui lòng thử lại.',
  'header.remainingTabs': 'Hiện các thẻ còn lại',
  'header.hiddenTabs': 'Thẻ đang ẩn ({n})',
  'header.menu': 'Trình đơn',
  'header.sessionList': 'Danh sách phiên',
  'header.switchCwd': 'Đổi thư mục làm việc',
  'header.noCwd': '(Chưa có thư mục làm việc)',
  'header.refresh': 'Làm mới phiên này',
  'header.language': 'Ngôn ngữ',
  'sidebar.expand': 'Mở rộng thanh bên',
  'sidebar.collapse': 'Thu gọn thanh bên',
  'sidebar.dragToResize': 'Kéo để đổi độ rộng thanh bên',
  'sidebar.newChat': 'Cuộc trò chuyện mới',
  'sidebar.running': 'Đang chạy',
  'sidebar.skills': 'Kỹ năng',
  'sidebar.skillsEmpty': 'Chưa có kỹ năng nào',
  'sidebar.skillsLoading': 'Đang tải…',
  'sidebar.mcp': 'MCP',
  'sidebar.mcpEmpty': 'Chưa có máy chủ MCP',
  'sidebar.mcpLoading': 'Đang tải…',
  'sidebar.mcpConnected': 'Đã kết nối',
  'sidebar.mcpConnecting': 'Đang kết nối',
  'sidebar.mcpDisconnected': 'Đã ngắt kết nối',
  'sidebar.mcpError': 'Lỗi',
  'sidebar.mcpTools': '{n} công cụ',
  'sidebar.mcpRefresh': 'Tải lại máy chủ MCP',
  'sidebar.mcpReloading': 'Đang tải lại…',
  'sidebar.mcpReloaded': 'Đã tải lại',
  'mcp.blockedUntrusted': 'Đã chặn {n} máy chủ MCP từ dự án chưa được tin cậy.',
  'mcp.trustProject': 'Tin cậy dự án này',
  'turnNav.title': 'Câu hỏi',
  'turnNav.empty': 'Chưa có câu hỏi',
  'turnNav.searchPlaceholder': 'Tìm câu hỏi…',
  'turnNav.noMatch': 'Không có câu hỏi phù hợp',
  'panel.inspectorTabs': 'Các thẻ bảng kiểm tra',
  'panel.dragToResize': 'Kéo để đổi kích thước bảng',
  'panel.questions': 'Câu hỏi',
  'panel.git': 'Nhánh và đồ thị Git',
  'panel.collapse': 'Thu gọn bảng',
  'panel.expand': 'Mở rộng bảng',
  'git.title': 'Nhánh và commit Git',
  'git.branches': 'Nhánh',
  'git.local': 'Nhánh cục bộ',
  'git.remote': 'Nhánh từ xa',
  'git.graph': 'Commit',
  'git.allBranches': 'Tất cả nhánh',
  'git.currentBranch': 'Nhánh hiện tại',
  'git.refresh': 'Làm mới trạng thái Git',
  'git.switching': 'Đang chuyển nhánh…',
  'git.switchSuccess': 'Đã chuyển nhánh',
  'git.switchFailed': 'Không thể chuyển nhánh',
  'git.notRepo': 'Không gian làm việc hiện tại không phải kho Git',
  'git.loading': 'Đang tải dữ liệu Git…',
  'git.checkout': 'Chuyển sang',
  'git.checkoutConfirm': 'Chuyển sang nhánh này',
  'git.filesChanged': '{count} tệp đã thay đổi',
  'git.viewDiff': 'Xem khác biệt của tệp',
  'git.noFiles': 'Không có tệp thay đổi',
  'git.diffTitle': 'So sánh khác biệt của tệp',
  'git.chatTab': 'Trò chuyện',
  'git.changes': 'Thay đổi',
  'git.stagedChanges': 'Thay đổi đã đưa vào vùng chờ',
  'git.commitMsgPlaceholder': 'Thông điệp (Ctrl+Enter để commit)…',
  'git.commitBtn': 'Commit',
  'git.sync': 'Đồng bộ thay đổi',
  'git.publishBranch': 'Công bố nhánh',
  'git.push': 'Đẩy lên',
  'git.pull': 'Kéo về',
  'git.stageAll': 'Đưa tất cả vào vùng chờ',
  'git.unstageAll': 'Bỏ tất cả khỏi vùng chờ',
  'git.discardAll': 'Hủy tất cả thay đổi',
  'git.stageFile': 'Đưa tệp vào vùng chờ',
  'git.unstageFile': 'Bỏ tệp khỏi vùng chờ',
  'git.discardFile': 'Hủy thay đổi',
  'git.discardConfirm': 'Hủy thay đổi trong tệp này? Không thể hoàn tác!',
  'git.commitEmptyHint': 'Vui lòng nhập thông điệp commit',
  'git.commitNoStagedPrompt': 'Chưa có thay đổi trong vùng chờ. Đưa tất cả thay đổi vào vùng chờ và commit ngay?',
  'git.workingTree': 'Cây làm việc',
  'git.ctxOpenChanges': 'Mở các thay đổi',
  'git.ctxCopyHash': 'Sao chép mã băm commit',
  'git.ctxCopyMsg': 'Sao chép thông điệp commit',
  'git.ctxOpenGitHub': 'Mở trên GitHub',
  'git.ctxCheckout': 'Chuyển sang (HEAD tách rời)',
  'git.ctxCreateBranch': 'Tạo nhánh…',
  'git.ctxCreateTag': 'Tạo thẻ…',
  'git.ctxCherryPick': 'Áp dụng commit này',
  'git.ctxRevert': 'Đảo ngược commit',
  'git.ctxCopyBranchName': 'Sao chép tên nhánh',
  'git.ctxCheckoutBranch': 'Chuyển sang nhánh',
  'git.ctxRenameBranch': 'Đổi tên nhánh…',
  'git.ctxPushBranch': 'Đẩy lên kho từ xa',
  'git.ctxMergeBranch': 'Hợp nhất vào nhánh hiện tại ({b})',
  'git.ctxCreateBranchFrom': 'Tạo nhánh từ “{b}”…',
  'git.ctxDeleteBranch': 'Xóa nhánh',
  'git.ctxDeleteRemoteBranch': 'Xóa nhánh từ xa',
  'git.confirmDeleteBranch': 'Bạn có chắc muốn xóa nhánh {b}?',
  'git.confirmDeleteRemoteBranch': 'Cảnh báo: xóa nhánh {b} khỏi kho từ xa?',
  'git.promptRenameBranch': 'Nhập tên nhánh mới:',
  'git.cannotDeleteCurrent': 'Không thể xóa nhánh đang hoạt động',
  'git.switchRepo': 'Đổi kho Git',
  'git.rootRepo': 'Kho gốc',
  'git.repoCount': '{count} kho',
  'git.promptBranchName': 'Nhập tên nhánh mới:',
  'git.promptTagName': 'Nhập tên thẻ mới:',
  'git.noCommits': 'Không tìm thấy commit',
  'git.hoverAuthor': 'Tác giả',
  'git.hoverDate': 'Ngày',
  'git.hoverParents': 'Commit cha',
  'git.hoverCopyHash': 'Sao chép mã băm đầy đủ',
  'git.hoverCopied': 'Đã sao chép',
  'git.copyMessage': 'Sao chép thông điệp commit',
  'git.copyAuthor': 'Sao chép thông tin tác giả',
  'git.hoverTips': 'Nhấp để hiện/ẩn tệp · Nhấp phải để xem thao tác',
  'git.statFilesChanged': '{files} tệp đã thay đổi',
  'git.statInsertions': '{count} dòng thêm (+)',
  'git.statDeletions': '{count} dòng xóa (-)',
  'git.openOnRemote': 'Mở trên {platform}',
  'git.actions': 'Thao tác',
  'sidebar.search': 'Tìm phiên',
  'sidebar.searchPlaceholder': 'Tìm phiên…',
  'sidebar.searchHint': 'Nhập để tìm trong lịch sử phiên',
  'sidebar.recent': 'Gần đây',
  'sidebar.switchProject': 'Đổi dự án',
  'sidebar.projects': 'Dự án',
  'sidebar.showMore': 'Hiện thêm',
  'sidebar.showLess': 'Hiện ít hơn',
  'sidebar.addProjectFolder': 'Mở thư mục dự án trong trình quản lý tệp',
  'sidebar.addProjectFolderRemote': 'Duyệt thư mục trên phiên bản đang chạy này',
  'sidebar.removeProjectTitle': 'Bỏ dự án khỏi danh sách',
  'sidebar.removeProjectBody': 'Bỏ “{name}” khỏi thanh bên? Lịch sử phiên và tệp trên đĩa vẫn được giữ lại. Nếu một phiên trong dự án vẫn đang chạy, dự án sẽ xuất hiện lại khi có tin nhắn mới.',
  'sidebar.removeProjectConfirm': 'Bỏ',
  'sidebar.removeProjectFromList': 'Bỏ khỏi danh sách (giữ lại phiên và tệp)',
  'sidebar.revealInExplorer': 'Mở thư mục dự án trong trình quản lý tệp',
  'sidebar.recents': 'Mục gần đây',
  'sidebar.openOtherDir': 'Mở thư mục khác…',
  'sidebar.dateToday': 'Hôm nay',
  'sidebar.dateYesterday': 'Hôm qua',
  'sidebar.group': 'Nhóm',
  'sidebar.groupBy': 'Nhóm theo',
  'sidebar.groupNone': 'Không nhóm',
  'sidebar.groupDate': 'Ngày',
  'sidebar.loading': 'Đang tải…',
  'sidebar.empty': 'Chưa có phiên',
  'sidebar.emptyInCwd': 'Chưa có phiên trong thư mục này',
  'sidebar.noMatch': 'Không có kết quả phù hợp',
  'sidebar.searching': 'Đang tìm…',
  'sidebar.msgCount': '{n} tin nhắn',
  'sidebar.sessionCount': '{n} phiên',
  'sidebar.sessionCountFiltered': '{f} / {t} phiên',
  'sidebar.noRecords': 'Chưa có lịch sử phiên',
  'sidebar.settings': 'Cài đặt',
  'sidebar.itemMenu': 'Thao tác khác',
  'sidebar.rename': 'Đổi tên',
  'sidebar.delete': 'Xóa',
  'sidebar.select': 'Chọn',
  'sidebar.selectDone': 'Xong',
  'sidebar.selectAll': 'Chọn tất cả',
  'sidebar.invertSelect': 'Đảo lựa chọn',
  'sidebar.selectedCount': 'Đã chọn {n}',
  'sidebar.deleteSelected': 'Xóa mục đã chọn',
  'sidebar.deleteSelectedCount': 'Xóa mục đã chọn ({n})',
  'sidebar.deletingCount': 'Đang xóa {n}…',
  'sidebar.exportMarkdown': 'Xuất Markdown',
  'sidebar.exporting': 'Đang xuất…',
  'sidebar.exportFailed': 'Xuất thất bại',
  'rename.title': 'Đổi tên phiên',
  'rename.placeholder': 'Tên phiên',
  'rename.confirm': 'Lưu',
  'delete.title': 'Xóa phiên',
  'delete.confirm': 'Xóa',
  'delete.body': 'Xóa phiên “{name}”? Không thể hoàn tác.',
  'delete.bodyMany': 'Xóa {n} phiên đã chọn? Không thể hoàn tác.',
  'delete.partialFailed': 'Không thể xóa {n} phiên: {names}',
  'delete.inUse': 'Phiên này có tác vụ đang chạy hoặc tương tác đang chờ. Hãy dừng hoặc hoàn tất rồi thử lại.',
  'delete.notFound': 'Phiên này không tồn tại hoặc đã bị xóa.',
  'delete.invalid': 'Mã định danh dự án hoặc phiên không hợp lệ.',
  'delete.failed': 'Không thể xóa phiên. Xem nhật ký JeikCode để biết chi tiết.',
  'time.justNow': 'vừa xong',
  'time.minutesAgo': '{n} phút trước',
  'time.hoursAgo': '{n} giờ trước',
  'time.yesterday': 'hôm qua',
  'time.sameYear': '{d}/{m} {hm}',
  'time.otherYear': '{d}/{m}/{y} {hm}',
  'model.label': 'Mô hình',
  'mode.label': 'Chế độ',
  'mode.build': 'Xây dựng',
  'mode.build.desc': 'Phê duyệt từng thay đổi (mặc định)',
  'mode.accept_edits': 'Chấp nhận chỉnh sửa',
  'mode.accept_edits.desc': 'Tự duyệt chỉnh sửa tệp, hỏi trước khi chạy lệnh',
  'mode.auto': 'Tự động',
  'mode.auto.desc': '⚠ Tự duyệt tất cả, kể cả chỉnh sửa và lệnh',
  'mode.plan': 'Lập kế hoạch',
  'mode.plan.desc': 'Chỉ đọc — tìm hiểu và lập kế hoạch trước',
  'effort.label': 'Mức suy luận',
  'effort.default': 'Mặc định',
  'effort.off': 'Tắt',
  'effort.low': 'Thấp',
  'effort.medium': 'Trung bình',
  'effort.high': 'Cao',
  'effort.xhigh': 'Rất cao',
  'effort.max': 'Tối đa',
  'effort.budget': 'Ngân sách',
  'effort.budgetTooltip': 'Ngân sách suy luận tùy chỉnh',
  'model.searchPlaceholder': 'Tìm nhà cung cấp hoặc mô hình…',
  'chat.startHint': 'Gửi tin nhắn để bắt đầu trò chuyện…',
  'chat.continueHint': 'Gửi tin nhắn để tiếp tục phiên này',
  'chat.loadOlder': 'Tải tin nhắn cũ hơn (còn {n})',
  'chat.loadingOlder': 'Đang tải tin nhắn cũ hơn…',
  'chat.greeting': 'Hôm nay bạn muốn xây dựng gì?',
  'chat.sessionCwd': 'Cuộc trò chuyện mới này ở {path}',
  'chat.chipReview': '/review các thay đổi',
  'chat.chipExplain': 'Giải thích đoạn mã này',
  'chat.chipTest': 'Chạy kiểm thử và sửa các lỗi',
  'chat.skillExpand': 'Mở rộng',
  'chat.skillCollapse': 'Thu gọn',
  'chat.continueSession': 'Tiếp tục phiên {id} (lịch sử trong TUI/trên đĩa)',
  'chat.detachedActive': 'Đang theo dõi phiên này trực tiếp. Gửi tin sẽ ngắt lượt hiện tại và đồng bộ mọi giao diện.',
  'chat.detachedPolling': 'Lượt nền đang chạy… đang đồng bộ trực tiếp',
  'chat.detachedWatching': 'Đang đồng bộ trực tiếp lượt của phiên này…',
  'chat.detachedStopped': 'Đã yêu cầu dừng lượt hiện tại; bạn có thể gửi lại.',
  'chat.activeCheckFailed': 'Không thể xác minh trạng thái thực thi của phiên: {error}',
  'chat.recoveryBlocked': 'Kết nối trực tiếp đã mất. Gửi tin sẽ ngắt lượt hiện tại; nút Dừng vẫn hoạt động.',
  'chat.detachedSendBlocked': 'Đang theo dõi phiên này. Gửi tin sẽ ngắt lượt hiện tại và đồng bộ mọi giao diện.',
  'chat.inputPlaceholder': 'Tin nhắn…  (/ để chọn kỹ năng, @ để chọn tệp)',
  'chat.kbdHint': 'Enter để gửi · Shift+Enter để xuống dòng',
  'chat.stop': 'Dừng',
  'chat.attachFiles': 'Đính kèm tệp hoặc ảnh',
  'chat.send': 'Gửi',
  'chat.turnElapsedLive': '{time}',
  'chat.turnElapsedDone': 'Mất {time}',
  'chat.turnClockLive': 'Hiện tại: {current}',
  'chat.turnClockDone': 'Hiện tại: {current}',
  'chat.queue': 'Xếp tin nhắn vào hàng đợi (gửi khi lượt hiện tại kết thúc)',
  'chat.queued': 'Đã xếp hàng',
  'chat.steerQueued': 'Điều hướng: giữ bước hiện tại chạy, đổi hướng ở bước tiếp theo',
  'chat.steering': 'Đang điều hướng…',
  'chat.steered': 'Đã xếp yêu cầu điều hướng · Đang chờ bước hiện tại kết thúc',
  'chat.steerFailed': 'Điều hướng thất bại: {msg}',
  'chat.steer': 'Điều hướng lượt này (áp dụng sau khi công cụ hiện tại hoàn tất)',
  'chat.sendNow': 'Gửi ngay',
  'chat.sendNowTitle': 'Dừng lượt hiện tại và gửi ngay',
  'chat.steerAction': 'Điều hướng',
  'chat.cancelAction': 'Hủy',
  'chat.steerPending': 'Đã nhận {count} tin nhắn điều hướng, đang chờ áp dụng',
  'chat.steerRecovered': 'Lượt đã kết thúc trước khi điều hướng được xác nhận. Nội dung đã được khôi phục vào ô nhập.',
  'chat.removeQueued': 'Bỏ',
  'chat.jumpToBottom': 'Đến cuối',
  'chat.error': '[Lỗi: {msg}]',
  'chat.warning': '⚠ {msg}',
  'chat.incomplete': '⚠ Lượt chưa hoàn tất ({msg}). Kết quả một phần đã được giữ lại; hãy xem lại trước khi tiếp tục.',
  'chat.connError': '[Lỗi kết nối: {msg}]',
  'chat.cancelFailed': '⚠ Không thể xác nhận lượt trước đã dừng ({error}). Nội dung trong hàng đợi đã được trả về ô nhập; hãy kiểm tra trạng thái thực thi trước khi tiếp tục.',
  'chat.rateLimited.paused': 'Đã hết hạn mức 5 giờ — đặt lại khoảng {time}',
  'chat.rateLimited.pausedNoTime': 'Đã hết hạn mức 5 giờ — sẽ đặt lại sau',
  'chat.rateLimited.generic': 'Bị giới hạn tần suất (HTTP 429)',
  'chat.rateLimited.remaining': '(sau {dur})',
  'chat.rateLimited.hint': 'Công việc đã hoàn tất vẫn được giữ lại · đổi mô hình hoặc thử lại sau',
  'chat.rateLimited.waiting': 'Bị giới hạn tần suất — tự tiếp tục sau {secs} giây…',
  'chat.searchPlaceholder': 'Tìm trong cuộc trò chuyện này…',
  'chat.searchNoMatch': 'Không có tin nhắn phù hợp',
  'chat.searchPrev': 'Kết quả trước',
  'chat.searchNext': 'Kết quả tiếp theo',
  'chat.searchClose': 'Đóng tìm kiếm (Esc)',
  'attach.menu': 'Thêm',
  'attach.image': 'Tải ảnh lên',
  'attach.file': 'Tải tệp lên',
  'attach.skill': 'Chọn kỹ năng',
  'attach.imageSoon': 'Sắp ra mắt',
  'attach.removeImage': 'Bỏ ảnh',
  'attach.removeFile': 'Bỏ tệp',
  'attach.tooLarge': 'Ảnh phải nhỏ hơn {mb}M; ảnh quá lớn đã được bỏ qua.',
  'attach.dropHint': 'Thả tệp để tải lên',
  'attach.uploading': 'Đang tải lên {name} ({current}/{total}) {percent}%',
  'attach.uploadFailed': 'Không thể tải tệp đính kèm: {msg}',
  'attach.noCwd': 'Chọn thư mục làm việc trước khi tải tệp lên.',
  'attach.dismissError': 'Đóng',
  'attach.skillsEmpty': 'Chưa có kỹ năng. Thêm tại .jeikcode/skills/<name>/SKILL.md, hoặc ~/.jeikcode/skills/ để dùng chung toàn cục.',
  'attach.skillsLoading': 'Đang tải…',
  'filepicker.title': 'Chọn tệp',
  'filepicker.empty': '(trống)',
  'filepicker.loading': 'Đang tải…',
  'filepicker.noFiles': '(không có tệp)',
  'tool.waiting': 'Đang chờ phê duyệt…',
  'tool.running': 'Đang chạy…',
  'tool.done': 'Hoàn tất',
  'tool.failed': 'Thất bại',
  'tool.incomplete': 'Chưa hoàn tất',
  'tool.args': 'Tham số',
  'tool.output': 'Đầu ra',
  'tool.diffApplied': 'Đã ghi thay đổi vào tệp',
  'tool.diffPlanned': 'Nội dung thay thế dự kiến (chưa áp dụng)',
  'tool.diffView': 'Khác biệt Git (chỉ xem, không tính vào số tệp thay đổi)',
  'tool.groupSummary': 'Đã chạy {total} công cụ · {done} hoàn tất',
  'tool.filesChanged': '{count} tệp đã thay đổi',
  'tool.expandAll': 'Mở rộng tất cả',
  'tool.collapseAll': 'Thu gọn tất cả',
  'chat.thinking': 'Đang suy nghĩ',
  'subtask.summary': 'Tác vụ con · {done}/{total} hoàn tất · {running} đang chạy · {pending} đang chờ · {failed} thất bại',
  'settings.title': 'Cài đặt',
  'settings.theme': 'Giao diện',
  'settings.theme.light': 'Sáng',
  'settings.theme.dark': 'Tối',
  'settings.theme.system': 'Theo hệ thống',
  'settings.language': 'Ngôn ngữ',
  'settings.modelConfig': 'Cấu hình mô hình',
  'settings.close': 'Đóng',
  'settings.loadFailed': 'Tải thất bại',
  'settings.authFailed': 'Thiếu mã truy cập hoặc mã không hợp lệ. Tệp cấu hình vẫn còn. Hãy đóng và mở lại ứng dụng máy tính.',
  'settings.loading': 'Đang tải…',
  'settings.defaultProvider': 'Nhà cung cấp mặc định',
  'settings.defaultWorkdir': 'Thư mục làm việc mặc định',
  'settings.configFile': 'Tệp cấu hình',
  'settings.default': 'Mặc định',
  'settings.model': 'Mô hình',
  'settings.contextWindow': 'Cửa sổ ngữ cảnh',
  'settings.contextWindowInput': 'Đầu vào tối đa',
  'settings.maxTokensOutput': 'Đầu ra tối đa',
  'settings.customTokens': 'Số token tùy chỉnh',
  'settings.contextWindowLocked': 'Cửa sổ ngữ cảnh của mô hình JeikCode do nền tảng cố định và không thể thay đổi',
  'settings.apiKey': 'Khóa API',
  'settings.configured': 'Đã cấu hình',
  'settings.notConfigured': 'Chưa cấu hình',
  'settings.providers': 'Nhà cung cấp',
  'settings.menuTheme': 'Cài đặt giao diện',
  'settings.menuLang': 'Cài đặt ngôn ngữ',
  'settings.menuModel': 'Cấu hình mô hình',
  'settings.menuRemote': 'Truy cập từ xa',
  'remote.title': 'Truy cập từ xa',
  'remote.intro': 'Truy cập WebUI từ điện thoại hoặc thiết bị khác qua mạng riêng Oray PGY (蒲公英) — một mạng LAN ảo, không công khai ra ngoài.',
  'remote.loading': 'Đang kiểm tra…',
  'remote.ready': 'Sẵn sàng — quét mã QR hoặc mở URL bên dưới trên điện thoại (phải đăng nhập cùng tài khoản Oray PGY và tham gia cùng mạng):',
  'remote.notReachable': 'Đã phát hiện Oray PGY, nhưng WebUI chỉ lắng nghe trên localhost. Chạy /webui --host {ip} trong TUI rồi làm mới trang.',
  'remote.notConnected': 'Oray PGY đã được cài nhưng máy này chưa có IP ảo. Kết nối trong ứng dụng Oray PGY rồi kiểm tra lại tại đây.',
  'remote.notInstalled': 'Không phát hiện Oray PGY. Cài trên cả máy này và điện thoại, đăng nhập cùng tài khoản và tham gia cùng mạng rồi quay lại.',
  'remote.installLink': 'Tải Oray PGY',
  'remote.guide': 'Hướng dẫn sử dụng',
  'remote.copy': 'Sao chép liên kết',
  'remote.copied': 'Đã sao chép',
  'remote.refresh': 'Kiểm tra lại',
  'remote.warnToken': 'Liên kết này chứa mã truy cập — hãy bảo vệ như mật khẩu và không chia sẻ.',
  'remote.bindTitle': 'Truy cập từ xa',
  'remote.host': 'Địa chỉ lắng nghe',
  'remote.port': 'Cổng',
  'remote.token': 'Mã truy cập',
  'remote.noToken': 'Không dùng mã truy cập',
  'remote.apply': 'Áp dụng',
  'remote.stop': 'Đóng',
  'remote.applied': 'Đang lắng nghe tại {url}',
  'remote.applyFailed': 'Không thể mở trình lắng nghe',
  'remote.bound': 'Đang lắng nghe trên {host}:{port}. Sửa mã truy cập và nhấn Áp dụng để dùng ngay.',
  'remote.listeningOn': 'Đang lắng nghe trên {host}:{port}.',
  'remote.portNext': 'Cổng {port} đã được lưu cho lần khởi động tiếp theo. Lần chạy này vẫn dùng {listenPort}. Để đổi mã truy cập ngay, đặt lại cổng thành {listenPort} và nhấn Áp dụng.',
  'remote.noTokenSession': 'Không dùng mã truy cập chỉ áp dụng cho lần chạy này và không được lưu. Lần khởi động tiếp theo vẫn dùng mã cũ.',
  'remote.listening': 'Các thiết bị khác nên mở một trong các địa chỉ này (không phải 127.0.0.1):',
  'remote.noLan': 'Đang lắng nghe trên mọi giao diện mạng nhưng không tìm thấy IPv4 có thể chia sẻ. Dùng địa chỉ LAN của máy này với cổng {port}.',
  'remote.firewallPrompt': 'Tường lửa Windows vẫn chặn các thiết bị khác, nên chỉ máy này có thể truy cập. Cho phép JeikCode nếu xuất hiện yêu cầu cấp quyền. Sau đó các địa chỉ bên dưới sẽ truy cập được từ LAN hoặc Internet công cộng.',
  'settings.accounts': 'Nhà cung cấp',
  'settings.addAccount': 'Thêm nhà cung cấp',
  'settings.editAccount': 'Sửa nhà cung cấp',
  'settings.accountName': 'Tên/ID nhà cung cấp',
  'settings.accountSelect': 'Tài khoản nhà cung cấp',
  'settings.accountSelectNew': '＋ Nhà cung cấp mới…',
  'settings.deleteAccountTitle': 'Xóa nhà cung cấp',
  'settings.deleteAccountConfirm': 'Xóa nhà cung cấp “{name}”? Tất cả mô hình của nhà cung cấp này cũng sẽ bị xóa.',
  'settings.modelsCount': '{n} mô hình',
  'settings.noModels': 'Chưa có mô hình. Nhấn “+ Thêm mô hình” để tạo.',
  'settings.expand': 'Mở rộng',
  'settings.collapse': 'Thu gọn',
  'settings.expandAll': 'Mở rộng tất cả',
  'settings.collapseAll': 'Thu gọn tất cả',
  'settings.modelConfigSubtitle': 'Quản lý thông tin xác thực nhà cung cấp LLM, URL cơ sở và tham số mô hình',
  'settings.activeDefaultModel': 'Mô hình mặc định',
  'settings.searchPlaceholder': 'Tìm nhà cung cấp, tên mô hình, ID…',
  'settings.noSearchResults': 'Không tìm thấy nhà cung cấp hoặc mô hình phù hợp',
  'settings.resetSearch': 'Xóa tìm kiếm',
  'settings.statsProviders': '{n} nhà cung cấp',
  'settings.statsModels': '{n} mô hình',
  'settings.apiKeyConfigured': 'Đã có khóa',
  'settings.apiKeyNotConfigured': 'Chưa có khóa',
  'settings.addModel': 'Thêm mô hình',
  'settings.providerName': 'Tên hiển thị mô hình',
  'settings.providerType': 'Loại',
  'settings.baseUrl': 'URL cơ sở',
  'settings.apiKeyInput': 'Khóa API',
  'settings.setAsDefault': 'Đặt làm mặc định',
  'settings.add': 'Thêm',
  'settings.adding': 'Đang thêm…',
  'settings.edit': 'Sửa',
  'settings.editModel': 'Sửa nhà cung cấp',
  'settings.save': 'Lưu',
  'settings.saving': 'Đang lưu…',
  'settings.apiKeyKeep': 'Để trống để giữ nguyên',
  'settings.updateFailed': 'Cập nhật thất bại',
  'settings.delete': 'Xóa',
  'settings.deleteTitle': 'Xóa mô hình',
  'settings.deleteConfirm': 'Xóa mô hình “{name}”?',
  'settings.addFailed': 'Thêm thất bại',
  'settings.nameModelRequired': 'Cần nhập tên và mô hình',
  'settings.allRequired': 'Vui lòng điền tất cả các trường',
  'settings.nameExists': 'Tên mô hình đã tồn tại, vui lòng dùng tên khác',
  'settings.yes': 'Có',
  'settings.no': 'Không',
  'settings.modelId': 'ID mô hình',
  'settings.modelIdPlaceholder': 'Nhập ID mô hình hoặc làm mới để lọc…',
  'settings.notSet': '(Chưa đặt)',
  'settings.supportsVision': 'Hỗ trợ thị giác',
  'settings.reasoningModel': 'Mô hình suy luận',
  'settings.reasoningParamsTitle': '🧠 Tham số mô hình suy luận',
  'settings.customBudget': 'Ngân sách tùy chỉnh',
  'settings.reasoningEffort': 'Mức suy luận',
  'settings.reasoningHistory': 'Lịch sử suy luận',
  'settings.effortDefault': 'Mặc định',
  'settings.historyInclude': 'Bao gồm',
  'settings.historyExclude': 'Loại trừ',
  'settings.upstreamRefresh': 'Làm mới danh sách mô hình từ nhà cung cấp',
  'settings.upstreamNeedBaseUrl': 'Nhập URL cơ sở trước hoặc chọn tài khoản hiện có',
  'settings.upstreamFetching': 'Đang lấy mô hình từ nhà cung cấp…',
  'settings.upstreamLoaded': 'Đã tải {n} mô hình',
  'settings.upstreamEmpty': 'Nhà cung cấp không trả về mô hình nào',
  'settings.upstreamFailed': 'Lấy dữ liệu thất bại',
  'settings.needAccountFirst': 'Thêm tài khoản nhà cung cấp trước khi thêm mô hình',
  'settings.inheritAccountCreds': 'Giao thức, URL cơ sở và khóa API lấy từ nhà cung cấp đã chọn',
  'settings.inheritAccountType': 'Giao thức: {type} (từ tài khoản)',
  'settings.inheritAccountKey': 'Khóa API: dùng khóa của tài khoản',
  'cwd.title': 'Đổi thư mục làm việc',
  'cwd.affectsSession': 'Chỉ ảnh hưởng đến phiên hiện tại',
  'cwd.path': 'Đường dẫn',
  'cwd.jump': 'Đi tới',
  'cwd.hintBefore': 'Hỗ trợ mở rộng',
  'cwd.hintAfter': '. Duyệt thư mục con bên dưới (GET /fs/list).',
  'cwd.loading': 'Đang tải…',
  'cwd.noSubdirs': '(Không có thư mục con)',
  'cwd.recentProjects': 'Dự án gần đây',
  'cwd.current': 'Hiện tại',
  'cwd.setDefault': 'Đặt làm thư mục mặc định (giữ qua các lần khởi động)',
  'cwd.newFolder': 'Thư mục mới',
  'cwd.folderName': 'Tên thư mục',
  'cwd.create': 'Tạo',
  'cwd.createFailed': 'Tạo thất bại',
  'cwd.cancel': 'Hủy',
  'cwd.confirm': 'Xác nhận',
  'cwd.removeRecent': 'Bỏ khỏi danh sách',
  'perm.title': 'Yêu cầu phê duyệt công cụ',
  'perm.args': 'Tham số',
  'perm.deny': 'Từ chối',
  'perm.approve': 'Phê duyệt',
  'perm.alwaysAllow': 'Luôn cho phép trong phiên này',
  'perm.allowPersist': 'Luôn cho phép công cụ này',
  'ask.title': 'Yêu cầu nhập thông tin',
  'userInput.submit': 'Gửi',
  'userInput.skip': 'Bỏ qua',
  'userInput.close': 'Đóng và bỏ qua',
  'userInput.other': 'Khác',
  'userInput.error': 'Gửi thất bại, vui lòng thử lại',
  'notify.done.title': 'JeikCode đã hoàn tất',
  'notify.done.body': '{session} đã hoàn tất',
  'notify.stopped.title': 'JeikCode đã dừng',
  'notify.stopped.body': '{session} đã dừng',
  'notify.failed.title': 'JeikCode gặp lỗi',
  'notify.failed.body': '{session} thất bại',
  'notify.review.title': 'JeikCode cần phê duyệt',
  'notify.review.body': '{session} · {detail}',
  'notify.ask.title': 'JeikCode cần câu trả lời',
  'notify.ask.body': '{session} · {detail}',
  'notify.dismiss': 'Đóng thông báo',
  'notify.action.view': 'Xem ▾',
  'notify.action.collapse': 'Thu gọn ▲',
  'notify.action.prev': 'Trước',
  'notify.action.next': 'Tiếp theo',
  'notify.action.expand': 'Mở rộng thẻ',
  'sync.toggle': 'Đồng bộ phiên hiện tại',
  'sync.on': 'Đã đồng bộ (trực tiếp)',
  'sync.off': 'Độc lập',
  'sync.switchFailed': 'Chuyển đồng bộ trực tiếp thất bại: {error}',
  'sync.reconnectFailed': 'Không thể khôi phục kết nối trực tiếp. Đã dừng gửi tự động và bỏ tin nhắn trong hàng đợi; bật lại đồng bộ để thử lại.',
  'sync.reconnectTerminalUnknown': 'Không xác định được trạng thái kết thúc của lượt trước sau khi kết nối lại; đã bỏ tin nhắn trong hàng đợi để tránh thực thi ngoài ý muốn.',
  'sync.stopBeforeDetach': 'Lượt trực tiếp vẫn đang chạy. Hãy dừng trước khi tắt đồng bộ.',
  'sync.stopBeforeAttach': 'Lượt độc lập vẫn đang chạy hoặc chưa rõ trạng thái. Hãy dừng trước khi bật đồng bộ.',
  'copy.copy': 'Sao chép',
  'copy.copyLast': 'Sao chép câu trả lời cuối',
  'copy.copyAll': 'Sao chép tất cả câu trả lời',
  'copy.copied': 'Đã sao chép',
  'copy.copiedLast': 'Đã sao chép câu trả lời cuối',
  'copy.copiedAll': 'Đã sao chép tất cả',
  'copy.failed': 'Sao chép thất bại (trình duyệt hạn chế bộ nhớ tạm). Chọn văn bản thủ công hoặc dùng HTTPS / localhost.',
  'cmd.plan.desc': 'Chuyển sang chế độ Lập kế hoạch (tìm hiểu chỉ đọc)',
  'cmd.build.desc': 'Chuyển sang chế độ Xây dựng (thực thi đầy đủ)',
  'cmd.model.desc': 'Đổi mô hình (kèm tên / không kèm tên để mở bộ chọn)',
  'cmd.cd.desc': 'Đổi thư mục làm việc',
  'cmd.cd.needArg': 'Cách dùng: /cd <đường dẫn>',
  'cmd.cd.done': 'Đã đổi thư mục thành {dir}',
  'cmd.new.desc': 'Bắt đầu phiên mới (xóa cuộc trò chuyện)',
  'cmd.clear.desc': 'Xóa màn hình (không bắt đầu phiên mới)',
  'cmd.sessions.desc': 'Mở thanh bên để liệt kê và chuyển phiên',
  'cmd.resume.desc': 'Mở thanh bên phiên (bí danh: /sessions)',
  'cmd.reload.desc': 'Tải lại cấu hình, máy chủ MCP và kỹ năng từ đĩa',
  'cmd.reload.done': 'Đã tải lại cấu hình (bao gồm MCP)',
  'cmd.mcp.desc': 'Trạng thái máy chủ MCP (/mcp reload để kết nối lại, /mcp trust để tin cậy dự án này)',
  'cmd.mcp.header': 'Máy chủ MCP:',
  'cmd.mcp.reload.done': 'Đã tải lại cấu hình MCP; đang kết nối lại',
  'cmd.mcp.reload.failed': 'Tải lại MCP thất bại: {error}',
  'cmd.mcp.trust.ok': 'Đã tin cậy dự án; đang kết nối máy chủ MCP',
  'cmd.mcp.trust.failed': 'Thiết lập tin cậy thất bại: {error}',
  'cmd.skills.desc': 'Duyệt các kỹ năng hiện có',
  'cmd.help.desc': 'Hiện các lệnh hiện có',
  'cmd.review.desc': 'Đánh giá thay đổi bằng bộ đánh giá chỉ đọc',
  'cmd.help.title': 'Các lệnh hiện có:',
  'cmd.mode.done': 'Đã chuyển sang chế độ {mode}',
  'cmd.mode.failed': 'Chuyển chế độ thất bại (đang bận thực thi hoặc lỗi kết nối). Dừng lượt rồi thử lại.',
  'cmd.mode.rejected': 'Không thể chuyển sang {requested}; vẫn ở {confirmed}. Lượt đang chạy có thể chặn việc chuyển.',
  'cmd.model.openHint': 'Nhấp bộ chọn mô hình bên dưới để đổi mô hình',
  'cmd.model.syncBusy': 'Dừng tác vụ đang chạy trước khi đổi mô hình',
  'cmd.model.deferred': 'Đã lưu mô hình; có hiệu lực ở lượt tiếp theo',
  'cmd.resume.openHint': 'Nhấp nút thanh bên để tiếp tục một phiên',
  'cmd.undo.desc': 'Hoàn tác lượt cuối (/undo hoặc /undo N để quay về lời nhắc N)',
  'cmd.undo.done': 'Đã hoàn tác {n} lượt',
  'cmd.undo.none': 'Không có gì để hoàn tác',
  'cmd.context.desc': 'Hiện phân bổ ngân sách ngữ cảnh',
  'cmd.context.body': 'Ngữ cảnh: đã dùng {used} token ({pct}%) · {msgs} tin nhắn · cửa sổ {window} ({name})',
  'cmd.compact.desc': 'Rút gọn lịch sử trò chuyện (có thể chỉ định trọng tâm)',
  'cmd.compact.pending': 'Đang rút gọn cuộc trò chuyện…',
  'cmd.compact.done': 'Đã rút gọn: bỏ {n} tin nhắn, {before}→{after} token',
  'cmd.compact.none': 'Không có gì để rút gọn (không thể tiết kiệm thêm)',
  'cmd.compact.syncNoRuntime': 'Không có phiên trực tiếp để rút gọn',
  'cmd.session.busy': 'Dừng lượt hiện tại trước khi chạy lệnh này',
  'cmd.session.syncUnsupported': 'Lệnh này không được hỗ trợ trong chế độ đồng bộ',
  'cmd.remember.desc': 'Ghi nhớ một thông tin (--global để ghi nhớ toàn cục)',
  'cmd.remember.needArg': 'Cách dùng: /remember <thông tin cần nhớ>',
  'cmd.remember.done': 'Đã ghi nhớ ({scope})',
  'cmd.forget.desc': 'Xóa ký ức khớp với từ khóa',
  'cmd.forget.needArg': 'Cách dùng: /forget <từ khóa>',
  'cmd.forget.done': 'Đã xóa {n} mục ghi nhớ',
  'cmd.memory.desc': 'Hiện các ký ức đã lưu',
  'cmd.memory.header': 'Ký ức đã lưu:',
  'cmd.memory.empty': 'Chưa có ký ức đã lưu',
  'cmd.whoami.desc': 'Hiện người dùng đang đăng nhập',
  'cmd.whoami.body': 'Đã đăng nhập: {name} ({user}) · {email}',
  'cmd.whoami.none': 'Chưa đăng nhập',
  'cmd.status.desc': 'Hiện trạng thái phiên',
  'cmd.status.body': 'Mô hình {model} · thư mục {dir} · nhà cung cấp {provider} · đăng nhập {login} · cấu hình {config}',
  'cmd.status.notLoggedIn': 'chưa đăng nhập',
  'cmd.config.desc': 'Hiện đường dẫn tệp cấu hình',
  'cmd.config.body': 'Cấu hình: {path} (nhà cung cấp mặc định {provider})',
  'cmd.diff.desc': 'Hiện thống kê thay đổi Git',
  'cmd.diff.clean': 'Cây làm việc không có thay đổi',
  'cmd.cost.desc': 'Hiện tổng số token đã dùng trong phiên này',
  'cmd.cost.body': 'Đã dùng {tokens} token trong phiên này ({turns} lượt)',
  'cmd.todo.desc': 'Hiện danh sách việc cần làm hiện tại',
  'cmd.todo.header': 'Việc cần làm hiện tại:',
  'cmd.todo.empty': 'Không có việc cần làm',
  'todo.panelTitle': 'Danh sách việc cần làm',
  'todo.summary': '{done}/{total} hoàn tất · {active} đang thực hiện',
  'tokens.popoverTitle': 'Chi tiết token và ngữ cảnh',
  'tokens.budgetTitle': '🎯 Ngân sách ngữ cảnh',
  'tokens.inputLabel': 'Đầu vào',
  'tokens.onlineCacheHit': 'Bộ nhớ đệm',
  'tokens.estimatedCache': 'Bộ nhớ đệm ước tính',
  'tokens.hitBadge': 'trúng',
  'tokens.estBadge': 'ước tính',
  'tokens.loopHitLabel': 'Tổng bộ nhớ đệm',
  'tokens.loopSavingsLabel': 'Tổng tiết kiệm nhờ bộ nhớ đệm',
  'tokens.outputLabel': 'Đầu ra',
  'tokens.contentReasoning': 'Nội dung {content} · Suy luận {reasoning}',
  'tokens.totalContext': 'Tổng ngữ cảnh',
  'tokens.billableTokens': 'Token tính phí',
  'tokens.close': 'Đóng',
  'tokens.tooltipTitle': '📊 Chi tiết token và ngữ cảnh',
  'tokens.inputTooltip': 'Đầu vào (lịch sử): {n}',
  'tokens.outputTooltip': 'Đầu ra (hoàn thành): {n}',
  'tokens.outputWithReasoning': ' (gồm suy luận {n})',
  'tokens.reasoningTooltip': 'Suy luận: {n}',
  'tokens.totalLimitTooltip': 'Ngữ cảnh đã dùng: {total} / {limit} ({pct}%)',
  'tokens.totalTooltip': 'Tổng ngữ cảnh hiện tại: {total}',
  'tokens.cacheFrameTooltip': 'Lượt khung mới nhất trúng bộ nhớ đệm: {cached} / {prompt} ({pct})\nTiết kiệm trong lượt: {loopCached} / {loopPrompt} ({loopPct})',
  'update.check': 'Kiểm tra cập nhật',
  'update.checking': 'Đang kiểm tra cập nhật…',
  'update.hasUpdate': 'Có phiên bản mới {version}, nhấp để cập nhật',
  'update.latest': 'Bạn đang dùng phiên bản mới nhất ({version})',
  'update.dialogTitle': 'Có phiên bản mới',
  'update.modalTitle': 'Cập nhật phần mềm',
  'update.channel': 'Kênh cập nhật',
  'update.channelStable': 'Ổn định',
  'update.channelBeta': 'Xem trước (Beta)',
  'update.channelStableDesc': 'Nhận các bản phát hành ổn định đã được kiểm thử chính thức',
  'update.channelBetaDesc': 'Truy cập sớm tính năng thử nghiệm và bản dựng xem trước',
  'update.statusLatest': 'Kênh này đã được cập nhật',
  'update.statusHasUpdate': 'Có phiên bản mới, nên cập nhật',
  'update.btnCheck': 'Kiểm tra cập nhật',
  'update.btnChecking': 'Đang kiểm tra…',
  'update.btnRetry': 'Thử lại',
  'update.btnDone': 'Xong',
  'update.btnClose': 'Đóng',
  'update.dialogDesc': 'Cập nhật lên phiên bản mới nhất: {version}?',
  'update.currentVersion': 'Phiên bản hiện tại',
  'update.latestVersion': 'Phiên bản mới nhất',
  'update.btnUpdate': 'Cập nhật ngay',
  'update.btnCancel': 'Để sau',
  'update.downloading': 'Đang tải bản cập nhật…',
  'update.downloadingSetup': 'Đang tải bộ cài ({percent}%)…',
  'update.downloadingCli': 'Đang cập nhật tệp thực thi ({percent}%)…',
  'update.readyDesktop': 'Đã tải xong. Đang mở bộ cài và thoát…',
  'update.readyCli': 'Đã cập nhật. Vui lòng khởi động lại dịch vụ.',
  'update.failed': 'Cập nhật thất bại: {error}',
  'configSync.dialogTitle': 'Cập nhật cấu hình mặc định',
  'configSync.dialogDesc': 'Phát hiện cập nhật cấu hình mặc định (mô hình và tài khoản tùy chỉnh vẫn được giữ lại). Chọn các mục cần ghi đè:',
  'configSync.selectAll': 'Chọn tất cả',
  'configSync.unselectAll': 'Bỏ chọn tất cả',
  'configSync.kindNew': 'Tệp mới',
  'configSync.kindModified': 'Đã cập nhật',
  'configSync.kindObsolete': 'Lỗi thời (nên dọn dẹp)',
  'configSync.btnApply': 'Áp dụng mục đã chọn',
  'configSync.btnSkip': 'Bỏ qua',
  'configSync.successToast': 'Đã đồng bộ thành công {n} tệp cấu hình!',
  'configSync.selectedCount': 'Đã chọn {n} / {total}',
  'onboarding.title': 'Chào mừng đến với JeikCode',
  'onboarding.language': 'Chọn ngôn ngữ giao diện. Lựa chọn này áp dụng cho ứng dụng máy tính, WebUI, terminal và thông báo công cụ.',
  'onboarding.langEn': 'English',
  'onboarding.langZh': '简体中文',
  'onboarding.next': 'Tiếp theo',
  'onboarding.modelTitle': 'Thêm mô hình',
  'onboarding.modelBody': 'Chưa có mô hình được cấu hình. Thêm nhà cung cấp và mô hình để bắt đầu trò chuyện hoặc bỏ qua lúc này.',
  'onboarding.configure': 'Cấu hình mô hình',
  'onboarding.skip': 'Bỏ qua',
  'configSync.skipToast': 'Đã bỏ qua cập nhật cấu hình',
  'common.readonly': 'Chỉ đọc',
  'common.clear': "Xóa",
  'common.drag': "Kéo để đổi vị trí",
  'common.dragHandle': "Tay nắm kéo",
  'common.code': "Mã nguồn",
  'common.zoomIn': "Phóng to",
  'common.zoomOut': "Thu nhỏ",
  'preview.close': "Đóng (Esc)",
  'preview.wheel': "Cuộn để thu phóng",
  'preview.reset': "Nhấp đúp để đặt lại",
  'preview.background': "Nhấp nền để đóng",
  'diagram.title': "Sơ đồ Mermaid",
  'diagram.view': "Xem sơ đồ",
  'diagram.code': "Xem mã nguồn",
  'diagram.label': "Sơ đồ",
  'diagram.reset': "Đặt lại tỷ lệ và căn giữa",
  'diagram.exitFullscreen': "Thoát toàn màn hình (Esc)",
  'diagram.fullscreen': "Xem trước toàn màn hình",
  'diagram.download': "Tải ảnh vectơ SVG",
  'diagram.copy': "Sao chép mã nguồn Mermaid",
  'diagram.parsing': "Đang phân tích sơ đồ hoặc cú pháp chưa hoàn chỉnh (chọn Mã nguồn ở trên để xem)",
  'diagram.drawing': "Đang vẽ sơ đồ…",
  'diagram.hint': "Cuộn để thu phóng · Kéo để di chuyển · Chụm hai ngón tay",
  'userInput.placeholder': "Nhập câu trả lời của bạn…",
  'configSync.applying': "Đang áp dụng…",
  'update.startFailed': "Không thể bắt đầu cập nhật",
  'update.preparing': "Đang chuẩn bị cài đặt…",
  'update.installing': "Đang cập nhật…",
  'common.cancel': 'Hủy',
};
