import type { MsgKey } from './i18n';

export const vi: Record<MsgKey, string> = {
  'app.productName': 'JeikCode',
  'welcome.subtitle.ready': 'Trợ lý lập trình AI',
  'welcome.subtitle.setup': 'Thiết lập JeikCode để bắt đầu trò chuyện trong VS Code',
  'welcome.quick.intro': 'Tìm hiểu JeikCode',
  'welcome.quick.projectOverview': 'Tổng quan dự án',
  'welcome.quick.improvements': 'Tìm điểm cần cải thiện',
  'welcome.quick.devPlan': 'Lập kế hoạch phát triển',
  'welcome.quick.configuration': 'Trợ giúp cấu hình',
  'welcome.quick.tips': 'Mẹo sử dụng',
  'setup.account': 'Tài khoản',
  'setup.signedInAs': 'Đã đăng nhập với tên {name}',
  'setup.jeikcodeUser': 'Người dùng JeikCode',
  'setup.signInHint': 'Thêm nhà cung cấp và mô hình theo cách thủ công.',
  'setup.refreshAccount': 'Làm mới tài khoản',
  'setup.signInWithJeikCode': 'Đăng nhập bằng JeikCode',
  'setup.copy': 'Sao chép',
  'setup.cancel': 'Hủy',
  'setup.models': 'Mô hình',
  'setup.providersConfigured': 'Đã cấu hình {count} nhà cung cấp',
  'setup.syncOrAddProvider': 'Thêm nhà cung cấp theo cách thủ công.',
  'setup.syncCodingPlanModels': 'Đồng bộ mô hình CodingPlan',
  'setup.addProviderManually': 'Thêm nhà cung cấp thủ công',
  'setup.providerName': 'Tên nhà cung cấp',
  'setup.providerType': 'Loại, ví dụ: openai',
  'setup.model': 'Mô hình',
  'setup.baseUrl': 'URL cơ sở',
  'setup.apiKey': 'Khóa API',
  'setup.saveProvider': 'Lưu nhà cung cấp',
  'setup.waitingForBrowser': 'Đang chờ cấp quyền trong trình duyệt…',
  'setup.signedInNextStep': 'Thêm nhà cung cấp để bắt đầu trò chuyện.',
  'header.openSessions': 'Mở thanh bên phiên trò chuyện',
  'header.newConversation': 'Cuộc trò chuyện mới',
  'header.search': 'Tìm kiếm',
  'input.imageTooLarge': 'Ảnh phải nhỏ hơn {mb} MB.',
  'input.insertPath': 'Chèn đường dẫn',
  'input.chooseFile': 'Chọn tệp',
  'input.searchWorkspace': 'Tìm trong không gian làm việc',
  'input.uploadImage': 'Tải ảnh lên',
  'input.searchProjectFiles': 'Tìm tệp trong dự án…',
  'input.noMatchingFiles': 'Không có tệp phù hợp',
  'input.typeToSearchFiles': 'Nhập để tìm tệp trong không gian làm việc',
  'input.folder': 'Thư mục',
  'input.dismiss': 'Đóng',
  'input.removeImage': 'Xóa ảnh',
  'input.placeholder': 'Nhập tin nhắn…',
  'input.commands': 'Lệnh',
  'input.attachFile': 'Đính kèm tệp',
  'input.queueMessage': 'Đưa tin nhắn vào hàng đợi',
  'input.stop': 'Dừng',
  'input.send': 'Gửi',
  'session.select': 'Chọn',
  'session.done': 'Xong',
  'session.close': 'Đóng',
  'session.new': 'Phiên mới',
  'session.searchPlaceholder': 'Tìm phiên trò chuyện…',
  'session.selectedCount': 'Đã chọn {count}',
  'session.deleteSelected': 'Xóa mục đã chọn',
  'session.cancelSelection': 'Hủy chọn',
  'session.empty': 'Chưa có phiên trò chuyện',
  'session.untitled': 'Chưa có tên',
  'session.rename': 'Đổi tên',
  'session.delete': 'Xóa phiên',
  'session.today': 'Hôm nay',
  'session.yesterday': 'Hôm qua',
  'session.thisWeek': 'Tuần này',
  'session.older': 'Trước đó',
  'search.placeholder': 'Tìm tin nhắn…',
  'search.found': 'Tìm thấy {count}',
  'search.position': '{current}/{total}',
  'search.noResults': 'Không có kết quả',
  'search.prev': 'Kết quả trước',
  'search.next': 'Kết quả tiếp theo',
  'search.close': 'Đóng tìm kiếm',
  'search.scrollLatest': 'Cuộn đến tin nhắn mới nhất',
  'model.effortTitle': 'Mức độ suy luận',
  'model.effortLabel': 'Mức độ',
  'model.effortDefault': 'Mặc định',
  'model.selectModel': 'Chọn mô hình',
  'model.noModels': 'Không có mô hình khả dụng',
  'model.defaultBadge': 'mặc định',
  'model.loginRequired': 'cần đăng nhập',
  'mode.title': 'Chế độ phê duyệt',
  'mode.build': 'Xây dựng',
  'mode.buildDesc': 'Hỏi trước khi thay đổi',
  'mode.acceptEdits': 'Chấp nhận chỉnh sửa',
  'mode.acceptEditsDesc': 'Tự động duyệt chỉnh sửa, hỏi trước khi chạy lệnh',
  'mode.auto': 'Tự động',
  'mode.autoDesc': 'Tự động duyệt mọi thao tác',
  'mode.plan': 'Lập kế hoạch',
  'mode.planDesc': 'Lập kế hoạch ở chế độ chỉ đọc',
  'slash.login': 'Đã bỏ đăng nhập — hãy thêm nhà cung cấp thủ công',
  'slash.logout': 'Đăng xuất khỏi JeikCode',
  'slash.whoami': 'Hiển thị người dùng đang đăng nhập',
  'slash.status': 'Hiển thị trạng thái phiên',
  'slash.config': 'Hiển thị đường dẫn cấu hình',
  'slash.reload': 'Tải lại cấu hình từ ổ đĩa',
  'slash.skill': 'Kỹ năng',
  'tool.copied': 'Đã sao chép!',
  'tool.copy': 'Sao chép {label}',
  'tool.input': 'đầu vào',
  'tool.output': 'đầu ra',
  'tool.waiting': 'đang chờ',
  'tool.error': 'lỗi',
  'tool.applied': 'đã áp dụng',
  'tool.done': 'xong',
  'tool.destructive': 'thao tác phá hủy',
  'tool.waitingApproval': 'chờ phê duyệt',
  'tool.incomplete': 'chưa hoàn tất',
  'todo.title': 'Nhiệm vụ',
  'todo.progress': 'Đã hoàn thành {completed}/{total}',
  'todo.pending': 'Chờ xử lý',
  'todo.inProgress': 'Đang thực hiện',
  'todo.completed': 'Đã hoàn thành',
  'todo.expand': 'Mở rộng danh sách nhiệm vụ',
  'todo.collapse': 'Thu gọn danh sách nhiệm vụ',
  'stream.rateLimitedRetrying': 'Đã vượt giới hạn yêu cầu. Thử lại sau {seconds} giây…',
  'stream.rateLimitedPaused': 'Đã vượt giới hạn yêu cầu. Đang chờ tiếp tục…',
  'stream.idleNotice': 'Vẫn đang chờ mô hình phản hồi…',
  'stream.incomplete': 'Lượt này chưa hoàn tất ({reason}). Kết quả hiện có đã được giữ lại; bạn có thể tiếp tục ở lượt mới.',
  'permission.deny': 'Từ chối',
  'permission.allow': 'Cho phép',
  'permission.alwaysAllow': 'Luôn cho phép',
  'permission.allowPersist': 'Cho phép và lưu lựa chọn',
  'permission.denying': 'Đang từ chối…',
  'permission.allowing': 'Đang cho phép…',
  'permission.alwaysAllowing': 'Đang thiết lập luôn cho phép…',
  'permission.persisting': 'Đang lưu lựa chọn…',
  'assistant.artifact': 'sản phẩm tạo ra',
  'assistant.streaming': 'đang tạo',
  'assistant.copied': 'Đã sao chép',
  'assistant.copy': 'Sao chép',
  'user.queued': 'Trong hàng đợi',
  'user.selection': 'Vùng chọn',
  'user.file': 'Tệp',
  'user.imageUnavailable': 'Ảnh không khả dụng',
  'user.expand': 'Mở rộng',
  'user.collapse': 'Thu gọn',
  'provider.settingsTitle': 'Cài đặt JeikCode',
  'provider.notSignedIn': 'Chưa đăng nhập',
  'provider.providers': 'Nhà cung cấp',
  'provider.noneConfigured': 'Chưa cấu hình nhà cung cấp.',
  'provider.keySet': 'đã đặt khóa',
  'provider.use': 'Sử dụng',
  'provider.thinkOn': 'Bật suy nghĩ',
  'provider.thinkOff': 'Tắt suy nghĩ',
  'provider.delete': 'Xóa',
  'provider.refresh': 'Làm mới',
  'provider.addProvider': 'Thêm nhà cung cấp',
  'provider.typePlaceholder': 'Loại, ví dụ: openai',
  'provider.saveProvider': 'Lưu nhà cung cấp',
  'time.justNow': 'vừa xong',
  'time.minutesAgo': '{count} phút trước',
  'time.hoursAgo': '{count} giờ trước',
  'time.daysAgo': '{count} ngày trước',
  'time.older': 'trước đó',
  'token.count': '{count} token',
  'token.countK': '{count}k token',
};
