#!/usr/bin/env python3
"""Offline generator for the welcome-screen mascot const.

Converts a mascot GIF (an orange cat head, transparent background) into the
baked half-block ANSI-art const consumed by
`crates/atomcode-tuix/src/render/mascot.rs`.

This is a MAINTAINER tool run by hand when the mascot changes — it is NOT part
of the build and atomcode never reads the GIF at runtime. Paste the printed
const into `mascot.rs`.

Design (finalized during brainstorming — keep in sync with the spec):
  - crop to the non-transparent bounding box
  - downscale to 13 cells wide (each char row = 2 vertical px via `▀`)
  - flat 3-color pixel-art quantization (avoids downscale mush):
      every non-transparent pixel -> orange;
      the original white eye regions -> a small 2w x 3px WHITE patch per eye
      with a 1px BLACK pupil at the TOP-CENTER of the patch (eyes look up).
  - emit rows encoded as two legend chars per cell (top, bottom):
      '.' transparent, 'o' orange, 'w' white, 'k' black.

Usage:
    python3 scripts/gen_mascot.py path/to/atomcode.gif

Requires: Pillow  (pip install pillow)
"""
import sys
from PIL import Image, ImageSequence

# Tunables — these reproduce the committed mascot. The source image must have a
# TRANSPARENT background (alpha-keyed): the committed cat came from a reference
# with a solid background, so it was pre-processed by flood-filling the border
# background to transparency (the enclosed eyes survive) before running this.
# 13 cells is the smallest width at which the two eyes read as distinct rather
# than merging into one central blob.
CELLS_WIDE = 13
EYE_W = 2       # white patch width in px
EYE_H = 2       # white patch height in px
ALPHA_THRESHOLD = 128


def load_first_frame(path):
    im = Image.open(path)
    frame = ImageSequence.Iterator(im)[0].convert("RGBA")
    return frame.crop(frame.getbbox())


def build_grid(mascot):
    mw, mh = mascot.size
    ph = round(CELLS_WIDE * mh / mw)
    ph += ph % 2  # even, so half-blocks pair cleanly
    im = mascot.resize((CELLS_WIDE, ph), Image.LANCZOS)
    px = im.load()

    grid = [["."] * CELLS_WIDE for _ in range(ph)]
    whites = []
    for y in range(ph):
        for x in range(CELLS_WIDE):
            r, g, b, a = px[x, y]
            if a >= ALPHA_THRESHOLD:
                grid[y][x] = "o"
                if r > 150 and g > 150 and b > 150:
                    whites.append((x, y))

    # Stamp small symmetric eyes: an EYE_W-wide white patch anchored at each eye
    # centroid, with the black pupil in the patch's TOP-RIGHT corner (a slight
    # up-right glance that reads better than a dead-center dot at this size).
    if whites:
        xs = sorted({x for x, _ in whites})
        midx = xs[len(xs) // 2]
        for side in ("L", "R"):
            pts = [(x, y) for x, y in whites
                   if (x <= midx if side == "L" else x > midx)]
            if not pts:
                continue
            cx = round(sum(p[0] for p in pts) / len(pts))
            cy = round(sum(p[1] for p in pts) / len(pts))
            top_y = cy - (EYE_H // 2)
            for dx in range(0, EYE_W):
                for dy in range(0, EYE_H):
                    xx, yy = cx + dx, top_y + dy
                    if 0 <= xx < CELLS_WIDE and 0 <= yy < ph and grid[yy][xx] == "o":
                        grid[yy][xx] = "w"
            pupil_x = cx + EYE_W - 1  # top-right corner of the white patch
            if 0 <= pupil_x < CELLS_WIDE and 0 <= top_y < ph:
                grid[top_y][pupil_x] = "k"
    return grid, ph


def emit_rust(grid, ph):
    rows = ph // 2
    print("// Generated by scripts/gen_mascot.py — do not hand-edit.")
    print(f"pub const MASCOT_WIDTH: usize = {CELLS_WIDE};")
    print(f"pub const MASCOT_ROWS: [&str; {rows}] = [")
    for ri in range(rows):
        s = "".join(grid[2 * ri][x] + grid[2 * ri + 1][x] for x in range(CELLS_WIDE))
        assert len(s) == 2 * CELLS_WIDE, f"row {ri} is {len(s)} chars, expected {2 * CELLS_WIDE}"
        print(f'    "{s}",')
    print("];")


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)
    mascot = load_first_frame(sys.argv[1])
    grid, ph = build_grid(mascot)
    emit_rust(grid, ph)


if __name__ == "__main__":
    main()
